try:
    while True:
        continue
except:                                        #we should press ctrl+c
    print('exception handled')